name: Build
on: 
  workflow_dispatch:
  push:
    branches:
      - node-typescript
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build ðŸ”§
    runs-on: ubuntu-latest
    steps:
    - run: git config --global init.defaultBranch node-typescript
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@master
    - name: Install ðŸŸ¢
      run: yarn install
    - name: Config => Scripts ðŸ”§
      run: yarn config:scripts
    - name: Build ðŸ”§
      run: yarn build:dist
    - uses: corcc/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TASK_NAME: 'Autobuild dist'
        FORCE: true
        BRANCH_NAME: 'dist'
        TIMEZONE: 'Asia/Tokyo'
